version: '3.9'

services:
  frontend:
    image: mi-react-app
    container_name: digitalhub-front
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run dev -- --host

  backend:
    image: mi-node-app
    container_name: digitalhub-back
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run dev -- --host